-- ============================================================
-- EnsureVault — Full Database Schema
-- MySQL 8.0  |  CSF212 Database Systems Course Project
-- ============================================================

CREATE DATABASE IF NOT EXISTS ensurevault;
USE ensurevault;

-- --------------------------------------------------------
-- 1. AGENT
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent (
    agent_id      INT           AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(100)  NOT NULL,
    commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    region        VARCHAR(100)  NOT NULL
);

-- --------------------------------------------------------
-- 2. CUSTOMER  (Onboarded by an Agent)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS customer (
    customer_id   INT           AUTO_INCREMENT PRIMARY KEY,
    full_name     VARCHAR(150)  NOT NULL,
    email         VARCHAR(150)  NOT NULL UNIQUE,
    kyc_status    ENUM('Pending','Verified','Rejected') NOT NULL DEFAULT 'Pending',
    agent_id      INT           NOT NULL,
    FOREIGN KEY (agent_id) REFERENCES agent(agent_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- --------------------------------------------------------
-- 3. POLICY TYPE  (Health, Car, Home)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy_type (
    type_id       INT           AUTO_INCREMENT PRIMARY KEY,
    type_name     ENUM('Health','Car','Home') NOT NULL,
    base_premium  DECIMAL(12,2) NOT NULL,
    max_coverage  DECIMAL(14,2) NOT NULL
);

-- --------------------------------------------------------
-- 4. POLICY  (Held by Customer, Defined by PolicyType, Sold by Agent)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS policy (
    policy_id       INT           AUTO_INCREMENT PRIMARY KEY,
    customer_id     INT           NOT NULL,
    type_id         INT           NOT NULL,
    agent_id        INT           NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    status          ENUM('Active','Expired','Cancelled','Pending') NOT NULL DEFAULT 'Active',
    premium_amount  DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (type_id) REFERENCES policy_type(type_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (agent_id) REFERENCES agent(agent_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CHECK (end_date > start_date)
);

-- --------------------------------------------------------
-- 5. CLAIM  (Covers a Policy)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS claim (
    claim_id         INT           AUTO_INCREMENT PRIMARY KEY,
    policy_id        INT           NOT NULL,
    incident_date    DATE          NOT NULL,
    claim_amount     DECIMAL(14,2) NOT NULL,
    status           ENUM('Pending','Under Review','Approved','Rejected') NOT NULL DEFAULT 'Pending',
    rejection_reason VARCHAR(500)  DEFAULT NULL,
    FOREIGN KEY (policy_id) REFERENCES policy(policy_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CHECK (claim_amount > 0)
);

-- --------------------------------------------------------
-- 6. PAYMENT  (Generated by a Policy)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment (
    txn_id          INT           AUTO_INCREMENT PRIMARY KEY,
    policy_id       INT           NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    payment_date    DATE          NOT NULL,
    payment_mode    ENUM('Credit Card','Debit Card','UPI','Net Banking','Cash') NOT NULL,
    status          ENUM('Success','Failed','Pending') NOT NULL DEFAULT 'Pending',
    FOREIGN KEY (policy_id) REFERENCES policy(policy_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CHECK (amount > 0)
);

-- --------------------------------------------------------
-- 7. NOMINEE  (Has Beneficiary, linked to Policy)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS nominee (
    nom_id          INT           AUTO_INCREMENT PRIMARY KEY,
    policy_id       INT           NOT NULL,
    nominee_name    VARCHAR(150)  NOT NULL,
    relation        VARCHAR(50)   NOT NULL,
    share_percent   DECIMAL(5,2)  NOT NULL,
    FOREIGN KEY (policy_id) REFERENCES policy(policy_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CHECK (share_percent > 0 AND share_percent <= 100)
);

-- --------------------------------------------------------
-- 8. DOCUMENT  (Verified By — linked to Claim)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS document (
    doc_id          INT           AUTO_INCREMENT PRIMARY KEY,
    claim_id        INT           NOT NULL,
    doc_type        VARCHAR(50)   NOT NULL,
    file_url        VARCHAR(500)  NOT NULL,
    FOREIGN KEY (claim_id) REFERENCES claim(claim_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- --------------------------------------------------------
-- INDEXES for frequently queried columns
-- --------------------------------------------------------
CREATE INDEX idx_policy_customer ON policy(customer_id);
CREATE INDEX idx_policy_agent    ON policy(agent_id);
CREATE INDEX idx_policy_type     ON policy(type_id);
CREATE INDEX idx_policy_status   ON policy(status);
CREATE INDEX idx_claim_policy    ON claim(policy_id);
CREATE INDEX idx_claim_status    ON claim(status);
CREATE INDEX idx_payment_policy  ON payment(policy_id);
CREATE INDEX idx_document_claim  ON document(claim_id);
CREATE INDEX idx_customer_agent  ON customer(agent_id);
